import type { Metadata } from 'next';
import AnimatedReveal from '@/components/AnimatedReveal';
import Section from '@/components/Section';
import SectionLabel from '@/components/SectionLabel';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'PreCalIQ Terms of Service. Review the terms governing your use of the PreCalIQ AI-powered preconstruction platform.',
  alternates: { canonical: 'https://precaliq.com/terms' },
};

export default function TermsPage() {
  return (
    <div>
      <Section bg="gradient" className="text-center py-8 md:py-10">
        <AnimatedReveal direction="fade">
          <SectionLabel light>Legal</SectionLabel>
        </AnimatedReveal>
        <AnimatedReveal direction="up" delay={100}>
          <h1 className="text-4xl md:text-[3rem] font-extrabold leading-tight tracking-tight">Terms of Service</h1>
        </AnimatedReveal>
        <AnimatedReveal direction="up" delay={200}>
          <p className="mt-4 text-sm text-white/50">Last updated: March 1, 2026</p>
        </AnimatedReveal>
      </Section>

      <Section bg="white">
        <AnimatedReveal direction="up">
          <div className="prose-rich space-y-8 text-charcoal-light leading-relaxed text-[1.0625rem]">
            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing or using PreCalIQ (the &ldquo;Service&rdquo;), operated by Caliber Technologies, you agree to be bound by these Terms of Service. If you are using the Service on behalf of a company, you represent that you have the authority to bind that entity to these terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">2. Description of Service</h2>
              <p>
                PreCalIQ is an AI-powered preconstruction platform that automates material takeoffs from construction specifications and architectural plans, generates multi-option bids, manages vendor pricing, and detects change orders. The Service is provided as a cloud-based software-as-a-service (SaaS) platform.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">3. User Accounts</h2>
              <p>
                You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate and complete information during registration. You are responsible for all activity that occurs under your account.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">4. Subscription Plans and Billing</h2>
              <p>
                The Service offers Free, Professional, and Enterprise plans. Paid plans are billed monthly or annually as selected. You may cancel at any time; cancellation takes effect at the end of the current billing period. Refunds are provided on a pro-rata basis for annual plans within the first 30 days.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">5. Your Data</h2>
              <p>
                You retain all ownership rights to the construction documents, takeoffs, bids, and other data you upload to or generate through the Service (&ldquo;Your Data&rdquo;). You grant PreCalIQ a limited license to process Your Data solely for the purpose of providing the Service. We do not use Your Data to train AI models or share it with third parties except as described in our Privacy Policy.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">6. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-6 mt-2 space-y-1.5">
                <li>Use the Service for any illegal purpose</li>
                <li>Attempt to gain unauthorized access to the Service or its systems</li>
                <li>Reverse engineer, decompile, or disassemble the Service</li>
                <li>Resell or redistribute access to the Service without authorization</li>
                <li>Upload malicious files or content</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">7. AI-Generated Output</h2>
              <p>
                The takeoffs, bids, and other outputs generated by PreCalIQ&apos;s AI are provided as professional aids and should be reviewed by qualified estimators before use. PreCalIQ does not guarantee the accuracy of AI-generated outputs and is not liable for errors in construction estimates, bids, or related decisions made based on such outputs.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">8. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, PreCalIQ and Caliber Technologies shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunity, arising from your use of the Service.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">9. Service Availability</h2>
              <p>
                We strive to maintain 99.9% uptime for Enterprise plans as specified in individual SLAs. For Free and Professional plans, we make commercially reasonable efforts to maintain availability but do not guarantee specific uptime levels. We may perform scheduled maintenance with reasonable advance notice.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">10. Termination</h2>
              <p>
                Either party may terminate the agreement at any time. Upon termination, you may export Your Data for 30 days, after which it will be permanently deleted. We reserve the right to suspend or terminate accounts that violate these terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">11. Governing Law</h2>
              <p>
                These Terms shall be governed by the laws of the State of Delaware, without regard to conflict of law provisions. Any disputes shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-charcoal mb-3">12. Contact</h2>
              <p>
                For questions about these Terms, contact us at <a href="mailto:legal@precaliq.com" className="text-navy hover:text-navy-light underline">legal@precaliq.com</a>.
              </p>
            </div>
          </div>
        </AnimatedReveal>
      </Section>
    </div>
  );
}
